create extension if not exists pgcrypto;

create table if not exists public.posts (
  id uuid primary key default gen_random_uuid(),
  author_id uuid not null references auth.users(id) on delete cascade,
  nickname text not null check (char_length(nickname) between 1 and 16),
  category text not null check (category in ('domestic','usa','free','meme')),
  title text not null check (char_length(title) between 1 and 80),
  content text not null check (char_length(content) between 1 and 2000),
  views integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  author_id uuid not null references auth.users(id) on delete cascade,
  nickname text not null check (char_length(nickname) between 1 and 16),
  content text not null check (char_length(content) between 1 and 80),
  created_at timestamptz not null default now()
);

alter table public.posts enable row level security;
alter table public.messages enable row level security;

create policy "posts are publicly readable" on public.posts for select using (true);
create policy "signed users create posts" on public.posts for insert to authenticated with check (auth.uid() = author_id);
create policy "owners update posts" on public.posts for update to authenticated using (auth.uid() = author_id);
create policy "owners delete posts" on public.posts for delete to authenticated using (auth.uid() = author_id);
create policy "messages are publicly readable" on public.messages for select using (true);
create policy "signed users create messages" on public.messages for insert to authenticated with check (auth.uid() = author_id);
create policy "owners delete messages" on public.messages for delete to authenticated using (auth.uid() = author_id);

alter publication supabase_realtime add table public.posts;
alter publication supabase_realtime add table public.messages;

create index if not exists posts_created_at_idx on public.posts(created_at desc);
create index if not exists messages_created_at_idx on public.messages(created_at desc);
